#!/usr/bin/env python3

import sys
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import QWidget
from PyQt5.QtGui import QPixmap
from PyQt5.QtGui import QPainter
from PyQt5.QtCore import QTimer

class Window(QWidget):
  def __init__(self):
    super().__init__()

    self.img = QPixmap("steve.png")
    self.setGeometry(0, 0, 500, 300)
    self.setWindowTitle("Fuck")

    timer = QTimer(self)
    timer.timeout.connect(self.update)
    timer.start(1000)

  def paintEvent(self, evt):
    print("paint called!!")
    painter = QPainter(self)
    painter.drawPixmap(0, 0, self.img)

if __name__ == '__main__':
  app = QApplication(sys.argv)
  window = Window()

  window.show()
  sys.exit(app.exec_())
